name: Generate OpenAPI SDK

on:
  push:
    branches: [main]
    paths:
      - 'backend/app/**/*.py'
      - 'backend/pyproject.toml'
  workflow_dispatch:

jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Install backend dependencies
        run: |
          cd backend
          poetry install
      
      - name: Export OpenAPI spec
        run: |
          cd backend
          poetry run python -m scripts.export_openapi
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Generate SDK
        run: |
          cd frontend
          npm run generate:sdk
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: regenerate OpenAPI SDK'
          branch: automated/sdk-update
          title: 'chore: Update OpenAPI SDK'
          body: |
            Automated SDK regeneration based on backend changes.
            
            - Exported OpenAPI spec from FastAPI
            - Regenerated TypeScript SDK using openapi-typescript-codegen
            
            This PR was automatically created by the GitHub Actions workflow.
